aliases:

  - &restore-cache
    keys:
      - dependencies-{{ checksum "package.json" }}
      - dependencies-

  - &save-cache
    key: dependencies-{{ checksum "package.json" }}
    paths: node_modules

  - &filter-only-master
    branches:
      only: master


defaults: &defaults
  working_directory: ~/react-auth-verification-context
  docker:
    - image: cimg/node:19.3.0

version: 2.1

orbs:
  codecov: codecov/codecov@3.2.4

jobs:
  install-dependencies:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/react-auth-verification-context
      - restore-cache: *restore-cache
      - run: |
          npm install --ignore-scripts --frozen-lockfile
      - save-cache: *save-cache
      - persist_to_workspace:
          root: .
          paths: .
  tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/react-auth-verification-context
      - run: npm run lint
      - run: npm run format
      - run: npm run test
      - store_artifacts:
          path: coverage
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/react-auth-verification-context
      - run: npm run build
workflows:
  version: 2
  build:
    jobs:
      - install-dependencies
      - tests:
          requires:
            - install-dependencies
      - codecov/upload
      - build:
          requires:
            - tests