defaults: &defaults
  working_directory: ~/react-auth-verification-context
  docker:
    - image: cimg/node:19.3.0

version: 2.1
orbs:
  codecov: codecov/codecov@3.2.4

jobs:
  install-dependencies:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/react-auth-verification-context
      - run: |
          npm install --ignore-scripts --frozen-lockfile
      - persist_to_workspace:
          root: .
          paths: .
  tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/react-auth-verification-context
      - run: npm run lint
      - run: npm run format
      - run: npm run test
      - store_artifacts:
          path: coverage
  codecov:
    <<: *defaults
    steps:
      - codecov/upload:
          file: {{ coverage_report_filepath }}
      - attach_workspace:
          at: ~/react-auth-verification-context
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/react-auth-verification-context
      - run: npm run build
workflows:
  version: 2
  build:
    jobs:
      - install-dependencies
      - tests:
          requires:
            - install-dependencies
      - codecov:
          requires:
            - tests
      - build:
          requires:
            - tests